version: '3.9'

services:
  apache2:
    image: repulsesubversion
    container_name: apache2
    ports: 
    - "80:80"
    - "443:443"
    volumes:
    - ./svn:/var/lib/svn
  #caddy:
    #image: custom-caddy
    #container_name: caddy
    #ports: 
    #- "80:80"
    #- "443:443"